'use client';

import React from 'react';
import jsPDF from 'jspdf';
import { FileText, Download, BarChart3, DoorOpen, AlertCircle, CreditCard, Sparkles } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { useStore } from '@/lib/store/useStore';
import { formatCurrency } from '@/lib/utils';

export default function ReportsPage() {
  const { students, rooms, complaints, payments } = useStore();

  const generateFullExecutivePDF = () => {
    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.setTextColor(37, 99, 235);
    doc.text('RoomZen Student Housing OS', 20, 20);

    doc.setFontSize(14);
    doc.setTextColor(50, 50, 50);
    doc.text('EXECUTIVE OPERATIONAL REPORT', 20, 32);

    doc.line(20, 36, 190, 36);

    doc.setFontSize(11);
    doc.text(`Generated Date: ${new Date().toLocaleDateString()}`, 20, 48);
    doc.text(`Total Students Enrolled: ${students.length}`, 20, 56);
    doc.text(`Total Rooms / Beds: ${rooms.length} Rooms / ${rooms.reduce((a, b) => a + b.capacity, 0)} Beds`, 20, 64);
    doc.text(`Active Occupancy Rate: ${Math.round((rooms.reduce((a, b) => a + b.occupied, 0) / rooms.reduce((a, b) => a + b.capacity, 0)) * 100)}%`, 20, 72);
    doc.text(`Total Complaints Logged: ${complaints.length} (${complaints.filter(c => c.status === 'resolved').length} Resolved)`, 20, 80);
    doc.text(`Total Revenue Collected: ${formatCurrency(payments.filter(p => p.status === 'paid').reduce((a, b) => a + b.amount, 0))}`, 20, 88);

    doc.line(20, 96, 190, 96);
    doc.setFontSize(10);
    doc.setTextColor(120, 120, 120);
    doc.text('Confidential Report generated by RoomZen Student Housing SaaS Platform.', 20, 110);

    doc.save('RoomZen_Executive_Report.pdf');
  };

  return (
    <div className="space-y-6">
      
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-extrabold text-slate-900 dark:text-white tracking-tight flex items-center gap-2.5">
            <FileText className="w-7 h-7 text-indigo-600" />
            Executive PDF & Analytics Reports
          </h1>
          <p className="text-sm text-slate-500 mt-1">
            Generate printable PDF summary reports for hostel occupancy, complaint resolution, and financials.
          </p>
        </div>

        <Button variant="primary" size="sm" onClick={generateFullExecutivePDF}>
          <Download className="w-4 h-4 mr-1.5" /> Download Full PDF Report
        </Button>
      </div>

      {/* Report Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        
        <Card hoverEffect>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-base">
              <DoorOpen className="w-5 h-5 text-blue-500" />
              Occupancy Matrix Report
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3 text-xs">
            <p className="text-slate-500">Breakdown of vacant beds, floor-by-floor occupancy rates, and room transfers.</p>
            <Button size="sm" variant="outline" className="w-full" onClick={generateFullExecutivePDF}>
              Export Occupancy PDF
            </Button>
          </CardContent>
        </Card>

        <Card hoverEffect>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-base">
              <AlertCircle className="w-5 h-5 text-amber-500" />
              AI Complaints Analytics
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3 text-xs">
            <p className="text-slate-500">Average resolution duration per category (HVAC, Plumbing, Wi-Fi, Electrical).</p>
            <Button size="sm" variant="outline" className="w-full" onClick={generateFullExecutivePDF}>
              Export Complaints PDF
            </Button>
          </CardContent>
        </Card>

        <Card hoverEffect>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-base">
              <CreditCard className="w-5 h-5 text-emerald-500" />
              Financial & Fee Invoicing
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3 text-xs">
            <p className="text-slate-500">Monthly hostel rent collections, pending mess fee dues, and utility bill reports.</p>
            <Button size="sm" variant="outline" className="w-full" onClick={generateFullExecutivePDF}>
              Export Revenue PDF
            </Button>
          </CardContent>
        </Card>

      </div>

    </div>
  );
}
